"""empty message

Revision ID: 2a393daa57a1
Revises: 
Create Date: 2025-11-12 10:41:19.219836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a393daa57a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('slang', sa.Integer(), nullable=False),
    sa.Column('rhyme_time', sa.Integer(), nullable=False),
    sa.Column('translate', sa.Integer(), nullable=False),
    sa.Column('contextual', sa.Integer(), nullable=False),
    sa.Column('chain', sa.Integer(), nullable=False),
    sa.Column('opposites', sa.Integer(), nullable=False),
    sa.Column('alpha_thon', sa.Integer(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=True)

    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('translated', sa.String(length=200), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word'))
        batch_op.drop_index(batch_op.f('ix_words_language'))

    op.drop_table('words')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_username'))

    op.drop_table('players')
    # ### end Alembic commands ###
